### ISSUE TITLE
Reduce the length of generated animation files

### ISSUE THREAD

**Issue by Gonhex** [Garhoogin/NitroPaint#9]
The `NANR` files generated by NitroPaint are currently unnecessarily big. This has various causes but all related to the `animationData`.

1)
When a sequence is in `Index+T` mode, each animation field is followed by 8 byte junk data. This is probably caused by a copy paste error. In the following three lines the last `sizeof(ANIM_DATA_SRT)` should be changed to `sizeof(ANIM_DATA_T)`.
https://github.com/Garhoogin/NitroPaint/blob/64738a03b54a6af72c5e80ba0afc4a268135392f/NitroPaint/nanr.c#L106
https://github.com/Garhoogin/NitroPaint/blob/64738a03b54a6af72c5e80ba0afc4a268135392f/NitroPaint/nanr.c#L166
https://github.com/Garhoogin/NitroPaint/blob/64738a03b54a6af72c5e80ba0afc4a268135392f/NitroPaint/nanr.c#L181

2)
https://github.com/Garhoogin/NitroPaint/blob/64738a03b54a6af72c5e80ba0afc4a268135392f/NitroPaint/nanr.h#L10-L13
I don't see a reason to add a padding field here. The original `NANR` files I observed don't "`BEEF`" after every index. My suggestion is to delete everything that depends on `ANIM_DATA.pad_` and add something like this behind the `ABNK` writer:
```c
//padding for DWORD alignment
BYTE pad = 0xFF;
while (stream->size % 4 != 0) {
	bstreamWrite(stream, &pad, 1);
}
```

3)
With the current structure, everything is saved as it lays in the buffer. This can cause many duplicates in the output stream if different frames do the same thing. It would be nice if multiple frames pointed to the same address, if the target data is identical.

---
About the animation viewer, I know it's in an early stage of development but I would like to use this issue to ask a few things.
* Is there a reason you didn't add [-][+] buttons for the `Sequence`? The sequences could also be named with the `LABL` data.
* Why doesn't it appear under `Menu -> File/New/`?
* Wouldn't it be really easy to add `NMAR` support? The data structure is almost identical to `NANR`. It has an `ABNK` and a `LABL` section. Well, it would collide with the names of the source files but apart from that I don't see an obstacle.

**Comment by Garhoogin** [comment]
Hey,

The size of Index+T being too large does look to be a bug, that should not be written the way it is. That should be a pretty straightforward fix.

As for the BEEF padding, the files that I observed seemed to do this as I recall, though I can double check this. In theory the padding should only be needed at the very end if it's misaligned I imagine, I can take a look at doing this as well.

As for the  layout of the data saved, currently yeah there is no code in place to attempt to condense the animation data. I wasn't sure if the size differences would be  enough to warrant implementing this but that is something I can get to implementing as well.

For the viewer, I just don't think I ever got around to adding +/- buttons for them. The naming with LABL should also be possible in NCER files, though is unimplemented there as of now as well. Most of NitroPaint's features are written as they come up, and mostly in Mario Kart DS, which does not make use of many of these features, which is probably why they haven't been implemented yet.  

Adding support for reading NMAR files should in theory be pretty simple, though I fear also making a viewer for those as well, I still want to clean up and finish the NMCR viewer.  

As of now I'm working on some stuff for CTGP, but once that cools off a bit I should be able to get to this stuff. Thanks for taking the time to leave such a detailed issue.

**Comment by Gonhex** [comment]
Thanks for the reply. I'm not sure how the indices are usually listed in `NANR` files. In the `NMAR`s I observed there is often just a `00 00` `01 00` (without BEEF in between) and the frames point either to 0x0 or to 0x2.

About the `NCER`, I strongly advise against using the included `LABL` for naming the cells. It looks like these and the `UEXT` section there are just copies of the ones in the corresponding `NANR` file.

**Comment by Gonhex** [comment]
Quick update about the BEEF padding on simple sequences. It looks like the other animation types that include translating need DWORD alignment, meaning my 2nd suggestion in the initial issue text above would break things. But it should be possible to just pad once after each sequence of indices, for example instead of
```
00 00 EF BE 01 00 EF BE 02 00 EF BE
``` 
generate
```
00 00 01 00 02 00 EF BE
```

**Comment by Garhoogin** [comment]
I finally got around to taking a look at this. I've corrected the wrong Index+T frames, and I've reworked it to only insert padding bytes when the data immediately following it requires an alignment. This should make just plain Index animations take about half the space as before.
On the subject of reducing the overall animation sizes by reusing bytes, I was able to get this working as of my latest commit (referenced above). It will do a search through the existing animation frame data for matching bytes (with proper alignment for the frame type of course). I know this isn't the most optimal solution of course (in terms of size), but it does produce sizes comparable to the sizes that g2dcvtr produced. 
I realize that trying to get the most optimal size of animation data by overlapping parts of animations with each other in a more intelligent manner may get slightly smaller file sizes, but I don't think this is exactly worth all that complexity. If you disagree, you can always just reopen this issue and let me know.

As for things like adding/deleting sequences, I think that was just something that had slipped my mind at the time. It would pobably be trivial to add, and may be able to get around to it today or soon. Same goes for creating a new NANR file. As for supporting NMAR files, given that the structure is what it is, maybe I can have NitroPaint treat NMAR as an alternate format of NANR files, like I have right now with NCGR/NCBR files. For now though, I'll mark this closed since the main bugs/issues at hand are tackled. :)
